In [2]:
# importing the necessary package and creating the test and train data sets
import pandas as pd

training_set = pd.read_excel("Data_Train.xlsx")
test_set = pd.read_excel("Test_set.xlsx")


In [3]:
import pandas_profiling
pandas_profiling.ProfileReport(training_set)

In [4]:
pandas_profiling.ProfileReport(test_set)

In [5]:
training_set.head() # seeing how the training data looks

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [6]:
print("\nFeatures/Columns : \n", training_set.columns)
print("\n\nNumber of Features/Columns : ", len(training_set.columns))
print("\nNumber of Rows : ",len(training_set))
print("\n\nData Types :\n", training_set.dtypes)

print("\n Contains NaN/Empty cells : ", training_set.isnull().values.any())

print("\n Total empty cells by column :\n", training_set.isnull().sum(), "\n\n")



Features/Columns : 
 Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')


Number of Features/Columns :  11

Number of Rows :  10683


Data Types :
 Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

 Contains NaN/Empty cells :  True

 Total empty cells by column :
 Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64 




In [7]:
print("\nEDA on Test Set\n")

print("\nFeatures/Columns : \n",test_set.columns)
print("\n\nNumber of Features/Columns : ",len(test_set.columns))
print("\nNumber of Rows : ",len(test_set))
print("\n\nData Types :\n", test_set.dtypes)
print("\n Contains NaN/Empty cells : ", test_set.isnull().values.any())
print("\n Total empty cells by column :\n", test_set.isnull().sum())


EDA on Test Set


Features/Columns : 
 Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info'],
      dtype='object')


Number of Features/Columns :  10

Number of Rows :  2671


Data Types :
 Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
dtype: object

 Contains NaN/Empty cells :  False

 Total empty cells by column :
 Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
dtype: int64


In [8]:
print("Original Length of Training Set : ", len(training_set))

training_set = training_set.dropna()

print("Length of Training Set after dropping NaN: ", len(training_set))

Original Length of Training Set :  10683
Length of Training Set after dropping NaN:  10682


### converting the data type to data-time format and adding new columns

In [9]:
training_set['Journey_Day'] = pd.to_datetime(training_set.Date_of_Journey, format='%d/%m/%Y').dt.day
training_set.head() # cheking the dataset after transformation

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  
0           24  
1            1  
2            9  
3           12  
4            1

In [10]:
training_set['Journey_Month'] = pd.to_datetime(training_set.Date_of_Journey, format='%d/%m/%Y').dt.month
training_set.head() # cheking the dataset after transformation

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  Journey_Month  
0           24              3  
1            1              5  
2            9              6  
3           12              5  
4            1              3

In [11]:
# Test Set
test_set['Journey_Day'] = pd.to_datetime(test_set.Date_of_Journey, format='%d/%m/%Y').dt.day
test_set['Journey_Month'] = pd.to_datetime(test_set.Date_of_Journey, format='%d/%m/%Y').dt.month
test_set.head()

Airline Date_of_Journey    Source Destination            Route  \
0        Jet Airways       6/06/2019     Delhi      Cochin  DEL → BOM → COK   
1             IndiGo      12/05/2019   Kolkata    Banglore  CCU → MAA → BLR   
2        Jet Airways      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
3  Multiple carriers      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
4           Air Asia      24/06/2019  Banglore       Delhi        BLR → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops              Additional_Info  \
0    17:30  04:25 07 Jun  10h 55m      1 stop                      No info   
1    06:20         10:20       4h      1 stop                      No info   
2    19:15  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3    08:00         21:00      13h      1 stop                      No info   
4    23:55  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Day  Journey_Month  
0            6              6  
1           12              5  
2           21              5  
3           21              5  
4           24              6

In [17]:
#training_set.drop(labels = 'Date_of_Journey', axis = 1, inplace = True)
print('training set after transformation')

training set after transformation


In [18]:
test_set.drop(labels = 'Date_of_Journey', axis = 1, inplace = True)
print('test set after transformation')
test_set.head()

test set after transformation


Airline    Source Destination            Route Dep_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK    17:30   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR    06:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK    19:15   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK    08:00   
4           Air Asia  Banglore       Delhi        BLR → DEL    23:55   

   Arrival_Time Duration Total_Stops              Additional_Info  \
0  04:25 07 Jun  10h 55m      1 stop                      No info   
1         10:20       4h      1 stop                      No info   
2  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3         21:00      13h      1 stop                      No info   
4  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Day  Journey_Month  
0            6              6  
1           12              5  
2           21              5  
3           21              5  
4           24              6

In [19]:
training_set.info() # checking the data types of all the columns

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10682 entries, 0 to 10682
Data columns (total 12 columns):
Airline            10682 non-null object
Source             10682 non-null object
Destination        10682 non-null object
Route              10682 non-null object
Dep_Time           10682 non-null object
Arrival_Time       10682 non-null object
Duration           10682 non-null object
Total_Stops        10682 non-null object
Additional_Info    10682 non-null object
Price              10682 non-null int64
Journey_Day        10682 non-null int64
Journey_Month      10682 non-null int64
dtypes: int64(3), object(9)
memory usage: 1.1+ MB


In [20]:
training_set.describe()

Price   Journey_Day  Journey_Month
count  10682.000000  10682.000000   10682.000000
mean    9087.214567     13.509081       4.708575
std     4611.548810      8.479363       1.164408
min     1759.000000      1.000000       3.000000
25%     5277.000000      6.000000       3.000000
50%     8372.000000     12.000000       5.000000
75%    12373.000000     21.000000       6.000000
max    79512.000000     27.000000       6.000000

In [24]:
duration = list(training_set['Duration'])
duration

['2h 50m',
 '7h 25m',
 '19h',
 '5h 25m',
 '4h 45m',
 '2h 25m',
 '15h 30m',
 '21h 5m',
 '25h 30m',
 '7h 50m',
 '13h 15m',
 '2h 35m',
 '2h 15m',
 '12h 10m',
 '2h 35m',
 '26h 35m',
 '4h 30m',
 '22h 35m',
 '23h',
 '20h 35m',
 '5h 10m',
 '15h 20m',
 '2h 50m',
 '2h 55m',
 '13h 20m',
 '15h 10m',
 '5h 45m',
 '5h 55m',
 '2h 50m',
 '2h 15m',
 '2h 15m',
 '13h 25m',
 '2h 50m',
 '22h',
 '5h 30m',
 '10h 25m',
 '5h 15m',
 '2h 30m',
 '6h 15m',
 '11h 55m',
 '11h 5m',
 '8h 30m',
 '22h 5m',
 '2h 45m',
 '12h',
 '2h 50m',
 '2h 50m',
 '2h 15m',
 '16h 5m',
 '19h 55m',
 '3h 15m',
 '25h 20m',
 '2h 50m',
 '3h',
 '2h 50m',
 '16h 15m',
 '15h 5m',
 '2h 15m',
 '6h 30m',
 '25h 5m',
 '12h 25m',
 '27h 20m',
 '10h 15m',
 '10h 30m',
 '2h 15m',
 '10h 25m',
 '2h 50m',
 '1h 30m',
 '13h 20m',
 '2h 15m',
 '1h 25m',
 '26h 30m',
 '7h 20m',
 '13h 30m',
 '5h',
 '2h 45m',
 '2h 50m',
 '1h 30m',
 '19h 5m',
 '2h 15m',
 '14h 50m',
 '2h 40m',
 '22h 10m',
 '9h 35m',
 '10h',
 '21h 20m',
 '5h 25m',
 '18h 45m',
 '12h 20m',
 '18h',
 '9h 15

In [25]:
duration.index

<function list.index(value, start=0, stop=9223372036854775807, /)>

In [26]:
for i in range(len(duration)) :
    if len(duration[i].split()) != 2: 
        if 'h' in duration[i] :
            duration[i] = duration[i].strip() + ' 0m'
        elif 'm' in duration[i] :
            duration[i] = '0h {}'.format(duration[i].strip())

In [27]:
dur_hours = []
dur_minutes = []  

for i in range(len(duration)) :
    dur_hours.append(int(duration[i].split()[0][:-1])) 
    #for examole if duration is 49 mintutes 4 sec then it will reflect like 
    dur_minutes.append(int(duration[i].split()[1][:-1]))
    #0:49:4 and if 2 hours 10 seconds then it will reflect like 2:0:10
    
training_set['Duration_hours'] = dur_hours
training_set['Duration_minutes'] =dur_minutes

training_set.drop(labels = 'Duration', axis = 1, inplace = True) 

training_set



Airline    Source Destination                  Route  \
0                 IndiGo  Banglore   New Delhi              BLR → DEL   
1              Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2            Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK   
3                 IndiGo   Kolkata    Banglore        CCU → NAG → BLR   
4                 IndiGo  Banglore   New Delhi        BLR → NAG → DEL   
5               SpiceJet   Kolkata    Banglore              CCU → BLR   
6            Jet Airways  Banglore   New Delhi        BLR → BOM → DEL   
7            Jet Airways  Banglore   New Delhi        BLR → BOM → DEL   
8            Jet Airways  Banglore   New Delhi        BLR → BOM → DEL   
9      Multiple carriers     Delhi      Cochin        DEL → BOM → COK   
10             Air India     Delhi      Cochin        DEL → BLR → COK   
11                IndiGo   Kolkata    Banglore              CCU → BLR   
12             Air India   Chennai     Kolkata              MAA → CCU   
13           Jet Airways   Kolkata    Banglore        CCU → BOM → BLR   
14                IndiGo   Kolkata    Banglore              CCU → BLR   
15             Air India     Delhi      Cochin  DEL → AMD → BOM → COK   
16              SpiceJet     Delhi      Cochin        DEL → PNQ → COK   
17           Jet Airways     Delhi      Cochin        DEL → BOM → COK   
18             Air India     Delhi      Cochin  DEL → CCU → BOM → COK   
19           Jet Airways     Delhi      Cochin        DEL → BOM → COK   
20                 GoAir     Delhi      Cochin        DEL → BOM → COK   
21             Air India  Banglore   New Delhi        BLR → COK → DEL   
22                IndiGo  Banglore       Delhi              BLR → DEL   
23                IndiGo  Banglore       Delhi              BLR → DEL   
24           Jet Airways   Kolkata    Banglore        CCU → BOM → BLR   
25           Jet Airways     Delhi      Cochin  DEL → IDR → BOM → COK   
26                IndiGo     Delhi      Cochin        DEL → LKO → COK   
27                 GoAir     Delhi      Cochin        DEL → BOM → COK   
28               Vistara  Banglore       Delhi              BLR → DEL   
29               Vistara   Chennai     Kolkata              MAA → CCU   
...                  ...       ...         ...                    ...   
10653        Jet Airways   Kolkata    Banglore        CCU → BOM → BLR   
10654           SpiceJet  Banglore       Delhi              BLR → DEL   
10655        Jet Airways    Mumbai   Hyderabad              BOM → HYD   
10656            Vistara  Banglore       Delhi              BLR → DEL   
10657        Jet Airways   Kolkata    Banglore        CCU → BOM → BLR   
10658        Jet Airways  Banglore       Delhi              BLR → DEL   
10659            Vistara  Banglore       Delhi              BLR → DEL   
10660            Vistara  Banglore   New Delhi              BLR → DEL   
10661          Air India     Delhi      Cochin        DEL → BOM → COK   
10662          Air India   Kolkata    Banglore  CCU → BOM → GOI → BLR   
10663        Jet Airways     Delhi      Cochin  DEL → JAI → BOM → COK   
10664             IndiGo  Banglore       Delhi              BLR → DEL   
10665             IndiGo   Kolkata    Banglore              CCU → BLR   
10666        Jet Airways     Delhi      Cochin        DEL → BOM → COK   
10667        Jet Airways  Banglore   New Delhi        BLR → BOM → DEL   
10668        Jet Airways     Delhi      Cochin  DEL → JDH → BOM → COK   
10669          Air India     Delhi      Cochin        DEL → BOM → COK   
10670          Air India   Kolkata    Banglore  CCU → IXR → DEL → BLR   
10671          Air India    Mumbai   Hyderabad              BOM → HYD   
10672        Jet Airways     Delhi      Cochin  DEL → AMD → BOM → COK   
10673        Jet Airways     Delhi      Cochin  DEL → AMD → BOM → COK   
10674        Jet Airways  Banglore   New Delhi        BLR → BOM → DEL   
10675          Air India    Mumbai   Hyderabad              BOM → HYD   
10

In [28]:
# Test Set(applyig same code to convert 'Duration' to 'Duration _Hours' and 'Duration_Minutes')
#2h 50m
durationT = list(test_set['Duration'])

for i in range(len(durationT)) :
    if len(durationT[i].split()[0]) != 2:       
        if 'h' in durationT[i] :
            durationT[i] = durationT[i].strip() + ' 0m'
        elif 'm' in durationT[i] :
            durationT[i] = '0h {}'.format(durationT[i].strip())

In [29]:
durationT

['10h 55m 0m',
 '4h',
 '23h 45m 0m',
 '13h 0m',
 '2h 50m',
 '18h 20m 0m',
 '15h 5m 0m',
 '5h 15m',
 '2h 45m',
 '6h 5m',
 '28h 55m 0m',
 '9h 20m',
 '10h 15m 0m',
 '4h 40m',
 '17h 20m 0m',
 '10h 50m 0m',
 '9h 15m',
 '12h 15m 0m',
 '9h 10m',
 '9h 20m',
 '14h 50m 0m',
 '14h 5m 0m',
 '11h 35m 0m',
 '13h 30m 0m',
 '2h 50m',
 '12h 25m 0m',
 '2h 30m',
 '25h 30m 0m',
 '19h 25m 0m',
 '7h',
 '2h 30m',
 '11h 40m 0m',
 '7h 5m',
 '3h',
 '1h 25m',
 '2h 40m',
 '1h 25m',
 '6h 5m',
 '17h 5m 0m',
 '10h 40m 0m',
 '2h 30m',
 '12h 30m 0m',
 '1h 30m',
 '23h 40m 0m',
 '5h 15m',
 '2h 20m',
 '23h 35m 0m',
 '1h 30m',
 '27h 40m 0m',
 '13h 30m 0m',
 '28h 20m 0m',
 '5h 45m',
 '26h 25m 0m',
 '5h 40m',
 '2h 15m',
 '2h 55m',
 '5h 45m',
 '7h 30m',
 '5h 20m',
 '25h 50m 0m',
 '13h 15m 0m',
 '26h 20m 0m',
 '5h 45m',
 '5h 40m',
 '2h 40m',
 '2h 50m',
 '5h 25m',
 '8h 45m',
 '3h',
 '7h 20m',
 '1h 30m',
 '21h 10m 0m',
 '16h 0m',
 '7h 50m',
 '1h 30m',
 '3h',
 '2h 50m',
 '19h 25m 0m',
 '2h 55m',
 '14h 5m 0m',
 '2h 50m',
 '16h 5m

In [30]:
dur_hours = []
dur_minutes = []  

for i in range(len(durationT)) :
    #print(durationT[i].split())
    dur_hours.append(int(durationT[i].split()[0][:-1]))
    if(len(durationT[i].split())>1):
        dur_minutes.append(int(durationT[i].split()[1][:-1]))
    else:
        dur_minutes.append(int(0))
  
    
test_set['Duration_hours'] = dur_hours
test_set['Duration_minutes'] = dur_minutes



In [32]:
#test_set['Duration_hours'] 
test_set['Duration_minutes'].head()

0    55
1     0
2    45
3     0
4    50
Name: Duration_minutes, dtype: int64

In [33]:
test_set.drop(labels = 'Duration', axis = 1, inplace = True)

In [34]:
training_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
Airline             10682 non-null object
Source              10682 non-null object
Destination         10682 non-null object
Route               10682 non-null object
Dep_Time            10682 non-null object
Arrival_Time        10682 non-null object
Total_Stops         10682 non-null object
Additional_Info     10682 non-null object
Price               10682 non-null int64
Journey_Day         10682 non-null int64
Journey_Month       10682 non-null int64
Duration_hours      10682 non-null int64
Duration_minutes    10682 non-null int64
dtypes: int64(5), object(8)
memory usage: 1.1+ MB


In [35]:
#Converting 'Dep_Time' to 'Depart_Time_hour' and 'Depart_time_Minutes'
training_set['Depart_Time_Hour'] = pd.to_datetime(training_set.Dep_Time).dt.hour
training_set['Depart_Time_Minutes'] = pd.to_datetime(training_set.Dep_Time).dt.minute

training_set.drop(labels = 'Dep_Time', axis = 1, inplace = True)

training_set.head() 

Airline    Source Destination                  Route  Arrival_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL  01:10 22 Mar   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR         13:15   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK  04:25 10 Jun   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR         23:30   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL         21:35   

  Total_Stops Additional_Info  Price  Journey_Day  Journey_Month  \
0    non-stop         No info   3897           24              3   
1     2 stops         No info   7662            1              5   
2     2 stops         No info  13882            9              6   
3      1 stop         No info   6218           12              5   
4      1 stop         No info  13302            1              3   

   Duration_hours  Duration_minutes  Depart_Time_Hour  Depart_Time_Minutes  
0               2                50                22                   20  
1               7                25                 5                   50  
2              19                 0                 9                   25  
3               5                25                18                    5  
4               4                45                16                   50

In [36]:
#Converting 'Arr_Time' to 'Arr_Time_hour' and 'Arr_time_Minutes' and dropping the original column
training_set['Arr_Time_Hour'] = pd.to_datetime(training_set.Arrival_Time).dt.hour
training_set['Arr_Time_Minutes'] = pd.to_datetime(training_set.Arrival_Time).dt.minute

training_set.drop(labels = 'Arrival_Time', axis = 1, inplace = True)
training_set.head() 

Airline    Source Destination                  Route Total_Stops  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    non-stop   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR     2 stops   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK     2 stops   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR      1 stop   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL      1 stop   

  Additional_Info  Price  Journey_Day  Journey_Month  Duration_hours  \
0         No info   3897           24              3               2   
1         No info   7662            1              5               7   
2         No info  13882            9              6              19   
3         No info   6218           12              5               5   
4         No info  13302            1              3               4   

   Duration_minutes  Depart_Time_Hour  Depart_Time_Minutes  Arr_Time_Hour  \
0                50                22                   20              1   
1                25                 5                   50             13   
2                 0                 9                   25              4   
3                25                18                    5             23   
4                45                16                   50             21   

   Arr_Time_Minutes  
0                10  
1                15  
2                25  
3                30  
4                35

In [30]:
#should have done it before
# applying the same to test set

test_set['Depart_Time_Hour'] = pd.to_datetime(test_set.Dep_Time).dt.hour
test_set['Depart_Time_Minutes'] = pd.to_datetime(test_set.Dep_Time).dt.minute


test_set.drop(labels = 'Dep_Time', axis = 1, inplace = True)
test_set.head() # cheking the test set after transformation

Airline    Source Destination            Route  Arrival_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK  04:25 07 Jun   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR         10:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK  19:00 22 May   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK         21:00   
4           Air Asia  Banglore       Delhi        BLR → DEL  02:45 25 Jun   

  Total_Stops              Additional_Info  Journey_Day  Journey_Month  \
0      1 stop                      No info            6              6   
1      1 stop                      No info           12              5   
2      1 stop  In-flight meal not included           21              5   
3      1 stop                      No info           21              5   
4    non-stop                      No info           24              6   

   Duration_hours  Duration_minutes  Depart_Time_Hour  Depart_Time_Minutes  
0              10                55                17                   30  
1               4                 0                 6                   20  
2              23                45                19                   15  
3              13                 0                 8                    0  
4               2                50                23                   55

In [37]:
test_set['Arr_Time_Hour'] = pd.to_datetime(test_set.Arrival_Time).dt.hour
test_set['Arr_Time_Minutes'] = pd.to_datetime(test_set.Arrival_Time).dt.minute

test_set.drop(labels = 'Arrival_Time', axis = 1, inplace = True)
test_set.head()

Airline    Source Destination            Route Dep_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK    17:30   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR    06:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK    19:15   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK    08:00   
4           Air Asia  Banglore       Delhi        BLR → DEL    23:55   

  Total_Stops              Additional_Info  Journey_Day  Journey_Month  \
0      1 stop                      No info            6              6   
1      1 stop                      No info           12              5   
2      1 stop  In-flight meal not included           21              5   
3      1 stop                      No info           21              5   
4    non-stop                      No info           24              6   

   Duration_hours  Duration_minutes  Arr_Time_Hour  Arr_Time_Minutes  
0              10                55              4                25  
1               4                 0             10                20  
2              23                45             19                 0  
3              13                 0             21                 0  
4               2                50              2                45

In [74]:
test_set.drop(labels = 'Additional_Info', axis = 1, inplace = True)
test_set.head()

Airline    Source Destination            Route Dep_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK    17:30   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR    06:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK    19:15   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK    08:00   
4           Air Asia  Banglore       Delhi        BLR → DEL    23:55   

  Total_Stops  Journey_Day  Journey_Month  Duration_hours  Duration_minutes  \
0      1 stop            6              6              10                55   
1      1 stop           12              5               4                 0   
2      1 stop           21              5              23                45   
3      1 stop           21              5              13                 0   
4    non-stop           24              6               2                50   

   Arr_Time_Hour  Arr_Time_Minutes  
0              4                25  
1             10                20  
2             19                 0  
3             21                 0  
4              2                45

In [76]:
training_set.drop(labels = 'Additional_Info', axis = 1, inplace = True)
training_set.head()

Airline    Source Destination                  Route Total_Stops  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    non-stop   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR     2 stops   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK     2 stops   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR      1 stop   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL      1 stop   

   Price  Journey_Day  Journey_Month  Duration_hours  Duration_minutes  \
0   3897           24              3               2                50   
1   7662            1              5               7                25   
2  13882            9              6              19                 0   
3   6218           12              5               5                25   
4  13302            1              3               4                45   

   Depart_Time_Hour  Depart_Time_Minutes  Arr_Time_Hour  Arr_Time_Minutes  
0                22                   20              1                10  
1                 5                   50             13                15  
2                 9                   25              4                25  
3                18                    5             23                30  
4                16                   50             21                35

In [77]:

Y_train = training_set.iloc[:,6].values  # 6 is the index of "Price" in the Training Set , setting it as the label column

# Independent Variables
X_train = training_set.iloc[:,training_set.columns != 'Price'].values # selects all columns except "Price"

X_train

array([['IndiGo', 'Banglore', 'New Delhi', ..., 20, 1, 10],
       ['Air India', 'Kolkata', 'Banglore', ..., 50, 13, 15],
       ['Jet Airways', 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       ['Jet Airways', 'Banglore', 'Delhi', ..., 20, 11, 20],
       ['Vistara', 'Banglore', 'New Delhi', ..., 30, 14, 10],
       ['Air India', 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [78]:
# Independent Variables for Test Set
X_test = test_set.iloc[:,:].values
X_test

array([['Jet Airways', 'Delhi', 'Cochin', ..., 55, 4, 25],
       ['IndiGo', 'Kolkata', 'Banglore', ..., 0, 10, 20],
       ['Jet Airways', 'Delhi', 'Cochin', ..., 45, 19, 0],
       ...,
       ['Jet Airways', 'Delhi', 'Cochin', ..., 35, 4, 25],
       ['Air India', 'Delhi', 'Cochin', ..., 15, 19, 15],
       ['Multiple carriers', 'Delhi', 'Cochin', ..., 20, 19, 15]],
      dtype=object)

In [79]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()

### Training Set 

In [80]:
X_train[:,0] = le1.fit_transform(X_train[:,0])
X_train

array([[3, 'Banglore', 'New Delhi', ..., 20, 1, 10],
       [1, 'Kolkata', 'Banglore', ..., 50, 13, 15],
       [4, 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 'Banglore', 'Delhi', ..., 20, 11, 20],
       [10, 'Banglore', 'New Delhi', ..., 30, 14, 10],
       [1, 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [81]:
X_train[:,1] = le1.fit_transform(X_train[:,1])
X_train

array([[3, 0, 'New Delhi', ..., 20, 1, 10],
       [1, 3, 'Banglore', ..., 50, 13, 15],
       [4, 2, 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 0, 'Delhi', ..., 20, 11, 20],
       [10, 0, 'New Delhi', ..., 30, 14, 10],
       [1, 2, 'Cochin', ..., 55, 19, 15]], dtype=object)

In [82]:
X_train[:,2] = le1.fit_transform(X_train[:,2])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [83]:
X_train[:,3] = le1.fit_transform(X_train[:,3])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [84]:
X_train[:,4] = le1.fit_transform(X_train[:,4])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [85]:
X_train[:,5] = le1.fit_transform(X_train[:,5])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

### Applying  similar operations on the Test Set

In [86]:
X_test[:,0] = le2.fit_transform(X_test[:,0])

X_test[:,1] = le2.fit_transform(X_test[:,1])

X_test[:,2] = le2.fit_transform(X_test[:,2])

X_test[:,3] = le2.fit_transform(X_test[:,3])

X_test[:,4] = le2.fit_transform(X_test[:,4])

X_test[:,5] = le2.fit_transform(X_test[:,5])
X_test

array([[4, 2, 1, ..., 55, 4, 25],
       [3, 3, 0, ..., 0, 10, 20],
       [4, 2, 1, ..., 45, 19, 0],
       ...,
       [4, 2, 1, ..., 35, 4, 25],
       [1, 2, 1, ..., 15, 19, 15],
       [6, 2, 1, ..., 20, 19, 15]], dtype=object)

In [87]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

In [88]:
X_train = sc_X.fit_transform(X_train)
X_train

array([[-0.41080484, -1.65835945,  2.41653414, ..., -0.2349499 ,
        -1.80043628, -0.8900139 ],
       [-1.26115217,  0.89001433, -0.97381203, ...,  1.36360731,
        -0.05090913, -0.5870944 ],
       [ 0.01436882,  0.04055641, -0.2957428 , ...,  0.0314763 ,
        -1.3630545 ,  0.0187446 ],
       ...,
       [ 0.01436882, -1.65835945,  0.38232644, ..., -0.2349499 ,
        -0.34249699, -0.2841749 ],
       [ 2.56541078, -1.65835945,  2.41653414, ...,  0.2979025 ,
         0.0948848 , -0.8900139 ],
       [-1.26115217,  0.04055641, -0.2957428 , ...,  1.63003351,
         0.82385444, -0.5870944 ]])

In [90]:
#X_test = sc_X.fit_transform(X_test)
x=pd.DataFrame(X_test)

In [91]:
x.head(5)

0  1  2   3    4  5   6  7   8   9   10  11
0  4  2  1  76  138  0   6  6  10  55   4  25
1  3  3  0  65   31  0  12  5   4   0  10  20
2  4  2  1  76  156  0  21  5  23  45  19   0
3  6  2  1  76   48  0  21  5  13   0  21   0
4  0  0  2  16  198  4  24  6   2  50   2  45

In [92]:
X_test = sc_X.fit_transform(X_test)
X_test

array([[ 0.01190758,  0.03256662, -0.29488167, ...,  1.58856014,
        -1.36170869,  0.02633999],
       [-0.42377921,  0.87708559, -0.97622158, ..., -1.69552975,
        -0.50932437, -0.27177067],
       [ 0.01190758,  0.03256662, -0.29488167, ...,  0.99145289,
         0.76925212, -1.46421332],
       ...,
       [ 0.01190758,  0.03256662, -0.29488167, ...,  0.39434564,
        -1.36170869,  0.02633999],
       [-1.29515278,  0.03256662, -0.29488167, ..., -0.79986887,
         0.76925212, -0.56988133],
       [ 0.88328115,  0.03256662, -0.29488167, ..., -0.50131524,
         0.76925212, -0.56988133]])

In [93]:
# applying similar operation on the Y labels
Y_train = Y_train.reshape((len(Y_train), 1)) 
Y_train = sc_X.fit_transform(Y_train)
Y_train = Y_train.ravel()
Y_train

array([ 1.23728754, -1.47530729, -0.53179604, ...,  1.59110426,
       -1.47530729, -0.53179604])